name: Test and build

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

#permissions:
#  contents: write

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4.7.0
        with:
          python-version-file: pyproject.toml
          cache: poetry
      - run: poetry install --with dev
      - name: Run pre-commit
        run: |
          poetry run pre-commit run -a --show-diff-on-failure
      - name: Test
        run: |
          poetry run pytest -svvv tests/
      - name: Build
        run: |
          poetry build
      - name: Store the distribution packages
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish_pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - test_and_build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/file-automation
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
